extends: hierarchical_v4_statsfusion.yaml

experiment:
  ablation_id: S1

model:
  use_motion: true
  use_ppg: false
  use_statistics: true
  use_long_context: false

decoder:
  use_semi_markov: false
